source 'http://rubygems.org'

gem 'rake'
gem 'rack', '1.2.1'
gem 'rails', '3.0.9'
gem 'mysql2', '< 0.3'
gem 'andand'
gem 'awesome_print'
gem 'bedrock', :path => 'vendor/gems/bedrock'
#gem 'compass', '>= 0.12.2'
#gem 'compass-rails', '>= 1.0.3'
gem 'dalli'
gem 'exception_notification'
gem 'google_drive'
gem 'haml', '<4.0'
gem 'sass'
gem 'json'
gem 'jammit'
#gem 'kaminari'
gem 'newrelic_rpm'
#gem 'nokogiri', '1.4.6'
#gem 'paperclip'
gem 'psych', '1.3.4'
#gem 'prawn'


