source 'http://rubygems.org'

gem 'rake'
gem 'rack', '1.2.1'
gem 'rails', '3.0.3'
gem 'mysql2', '< 0.3'
gem 'andand'
gem 'awesome_print'
#gem 'dalli'
gem 'exception_notification'
#gem 'kaminari'
gem 'json'
gem 'haml'
#gem 'nokogiri', '1.4.6'
#gem 'paperclip'
gem 'rgeo'
gem 'rgeo-geojson'
gem 'activerecord-mysql2spatial-adapter'
gem 'bedrock', :path => 'vendor/gems/bedrock'
