source 'http://rubygems.org'

gem 'rake'
gem 'rack', '1.2.1'
gem 'rails', '3.0.9'
gem 'mysql2', '< 0.3'
gem 'andand'
gem 'awesome_print'
gem 'bedrock', :path => 'vendor/gems/bedrock'
gem 'dalli'
gem 'exception_notification'
gem 'newrelic_rpm'
gem 'haml'
gem 'json'
gem 'jammit'
#gem 'kaminari'
#gem 'nokogiri', '1.4.6'
#gem 'paperclip'
gem 'prawn'
gem 'google_drive'

#gem 'statsd-ruby', '~> 0.4.0', :git => 'git://github.com/jeremy/statsd-ruby', :require => 'statsd'

