package_assets: on
embed_assets: off
compress_assets: off

javascripts:
  common:
    - public/javascripts/jquery-1.7.1.min.js
    - public/javascripts/underscore-min.js
    - public/javascripts/mustache.js
    - public/javascripts/d3.min.js
    - public/javascripts/bootstrap.min.js
    - public/javascripts/application.js
  mapping:
    - public/javascripts/leaflet.js

stylesheets:
  common:
    - public/stylesheets/960.css
    - public/stylesheets/theme.css
    - public/stylesheets/leaflet.css

