cloudmade_key: 194e5888480d4f9499b2f2099a793dbe
cloudmade_style: 998

layers:
  schools:
    template: "<a href='/schools/{{slug}}'>{{name}}</a><br/>{{SCHOOL_STREET_ADDRESS_2012}}<br/>Grades {{AUTHORIZED_GRADES_2012}}<br/>{{#others}}<br/><a href='/schools/{{slug}}'>{{name}}</a><br/>Grades {{grades}}<br/>{{/others}}"
    style_handler: "function(e) { return { fillColor: { 'P2': '#8DC63F', 'ES': '#8DC63F', 'K8': '#8DC63F', 'MS': '#F79421', 'HS': '#004270' }[e.properties.TEMPLATE] }; }"
    geometry_type: point
    style:
      radius: 10
      fillColor: '#22aa66'
      color: "#000"
      weight: 2
      opacity: 1
      fillOpacity: 1
  others:
    template: "{{name2}}<br/>{{address1}}"
    style:
      radius: 10
      fillColor: '#446699'
      color: "#000"
      weight: 2
      opacity: 1
      fillOpacity: 1
  districts:
    style:
      color: '#004270'
      weight: 4
      fillOpacity: 0
  
