cloudmade_key: 194e5888480d4f9499b2f2099a793dbe
cloudmade_style: 998

layers:
  sample:
    template: "{{address}}"
    style_handler: "function(e) {  }"
    style:
      color: '#0ad'
      weight: 1
      fillOpacity: 0.1
    names:
      proaddress: Address
    
