cloudmade_key: 194e5888480d4f9499b2f2099a793dbe
cloudmade_style: 998

layers:
  schools:
    template: "<a href='/schools/{{id}}'>{{SCHOOL_NAME_2011}}</a><br/>{{SCHOOL_STREET_ADDRESS_2011}}"
    style_handler: "function(e) { e.layer.options.fillColor = { 0: '#8DC63F', 1: '#F79421', 2: '#004270' }[e.properties.level]; }"
    style:
      radius: 10
      fillColor: '#22aa66'
      color: "#000"
      weight: 2
      opacity: 1
      fillOpacity: 1
  others:
    template: "{{name2}}<br/>{{address1}}"
    style:
      radius: 10
      fillColor: '#446699'
      color: "#000"
      weight: 2
      opacity: 1
      fillOpacity: 1
  districts:
    style:
      color: '#004270'
      weight: 4
      fillOpacity: 0
  
