common:
  typekit_key: rak2ush
  analytics_key:

development:
  analytics_key:
  fb_app_id: 
  fb_secret: 
 
staging:
  analytics_key: 
  fb_app_id: 
  fb_secret: 
  
production:
  analytics_key: 
  fb_app_id: 
  fb_secret: 
