common:
  typekit_key: rak2ush
  cache_key: 12
  analytics_key:

development:
  analytics_key:
  fb_app_id: 
  fb_secret: 
 
staging:
  analytics_key: 
  fb_app_id: 
  fb_secret: 
  
production:
  analytics_key: UA-34426035-1
  fb_app_id: 
  fb_secret: 
