common:
  typekit_key: rak2ush
  cache_key: 15
  analytics_key:
  max_compared: 5
  radius_mi: 2
  detroit_proj: +proj=utm +zone=17 +ellps=WGS84 +datum=WGS84 +units=m +no_defs

development:
  analytics_key:
  fb_app_id: 
  fb_secret: 
 
staging:
  analytics_key: 
  fb_app_id: 
  fb_secret: 
  
production:
  analytics_key: UA-34426035-1
  fb_app_id: 
  fb_secret: 
