local: &local
  adapter: mysql2spatial
  pool: 5
  timeout: 5000
  username: root
  password:
  host: localhost
  encoding: utf8

sage: &sage
  adapter: mysql2spatial
  pool: 5
  timeout: 5000
  username: rails
  password: huju5Azafu
  host: sage_private

development:
  <<: *local
  database: esd2_local

test:
  <<: *local
  database: esd2_test

staging:
  <<: *sage
  database: esd2_stage

production:
  <<: *sage
  database: esd2_prod


