local: &local
  adapter: mysql2spatial
  pool: 5
  timeout: 5000
  username: root
  password: 
  host: localhost
  encoding: utf8

dreamhost: &dreamhost
  adapter: mysql2spatial
  pool: 5
  timeout: 5000
  username: loveland_rails
  password: huju5Azafu
  host: db.lemonary.com
  encoding: utf8

lime: &lime
  adapter: mysql2spatial
  pool: 5
  timeout: 5000
  username: rails
  password: huju5Azafu
  host: localhost

development:
  <<: *local
  database: esd_local
  
test:
  <<: *local
  database: esd_test
  
staging:
  <<: *lime
  database: esd_stage

production:
  <<: *dreamhost
  database: esd_prod


