local: &local
  adapter: mysql2spatial
  pool: 5
  timeout: 5000
  username: root
  password: 
  host: localhost
  encoding: utf8

lime: &lime
  adapter: mysql2spatial
  pool: 5
  timeout: 5000
  username: rails
  password: huju5Azafu
  host: lime_private

development:
  <<: *local
  database: esd2_local
  
test:
  <<: *local
  database: esd2_test
  
staging:
  <<: *lime
  database: esd2_stage

production:
  <<: *lime
  database: esd2_prod


